version: "3"

services:

  nginx:
    container_name: nginx${PROJECT_NUMBER}
    image: kran13200/nginx:1.0.0
    # links:
    #   - ckan
    ports:
      - "0.0.0.0:${NGINX_PORT}:80"
    environment:
      - TZ=${TZ}
    networks:
      - ckan-networks
    
  ckan:
    container_name: ckan${PROJECT_NUMBER}
    image: thepaeth/ckan-thai_gdc:ckan-${CKAN_VERSION}-xloader
    env_file:
      - .env
    environment:
      - CKAN_SITE_URL=${DEFAULT_URL}:${NGINX_PORT}
    # links:
    #   - db
    #   - solr
    #   - redis
    volumes:
      - ckan_storage:/var/lib/ckan
    networks:
      - ckan-networks

  db:
    container_name: db-${PROJECT_NUMBER}
    # image: mdillon/postgis:11
    image: kran13200/db:1.0.0
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=ckan
      - POSTGRES_DB=ckan
      - PGDATA=/var/lib/postgresql/data/some_name/
      - TZ=${TZ}
    networks:
      - ckan-networks
    volumes:
      - pg_data:/var/lib/postgresql/data
     
  solr:
    container_name: solr${PROJECT_NUMBER}
    image: kran13200/solr:1.0.0
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index
    environment:
      - TZ=${TZ}
    networks:
      - ckan-networks

  redis:
    container_name: redis${PROJECT_NUMBER}
    image: redis:alpine
    networks:
      - ckan-networks

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      # PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "0.0.0.0:8080:80"
    networks:
      - ckan-networks
    restart: unless-stopped

volumes:
  ckan_storage:
  pg_data:
  solr_data:
  pgadmin:

networks:
  ckan-networks:
    driver: bridge
    # external: true
